[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
crc = "3.3.0"
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["blocking"] }
url = "2.5.4"
